<?php require_once(dirname(__FILE__) . "/escpos-php-master/Escpos.php");
							//$logo = new EscposImage("images/productos/tostao.jpg");
							$printer = new Escpos();
							/* Print top logo */
                            $printer -> setJustification(Escpos::JUSTIFY_CENTER);
                            //$printer -> graphics($logo);
							//$printer -> selectPrintMode(Escpos::MODE_DOUBLE_WIDTH);
							$printer -> text("PIRKAS BUNGALOWS");
							//$printer -> feed();
							//$printer -> selectPrintMode();
							$printer -> setJustification(Escpos::JUSTIFY_LEFT);
							$printer -> feed();
							$printer -> text("Ticket N°: 118");
							$printer -> feed();
							$printer -> text("Fecha y Hora: 2016-02-05 12:35:09\n");
							$printer -> text("Cajero: soporte");
							$printer -> feed();
							$printer -> text("Caja: Caja Principal");
							$printer -> text("  # Ref. Caja: 3");
							$printer -> feed();
							$printer -> text("----------------------------------------\n");
							$printer -> text("Concepto: ");
							$printer -> setEmphasis(true);
                            $printer -> text("Ingreso General nihuhihihii");
                            $printer -> setEmphasis(false);
                            //$printer -> feed();
                            //$printer -> text("Precio Unit. S/.: ");
                            //$printer -> text("3.00");
                            $printer -> feed();
                            $printer -> text("Cantidad: ");
                            $printer -> text("1. ");
                            //$printer -> feed();
                            $printer -> text("Bungalow: ");
                            //$printer -> setEmphasis(true);
                            //$printer -> text("0.00");
                            $printer -> text("202");
                            //$printer -> setEmphasis(false);
                            $printer -> feed();


							$printer -> text("----------------------------------------\n");$printer -> cut();$printer -> pulse();$printer -> close();