<?php require_once(dirname(__FILE__) . "/escpos-php-master/Escpos.php");
							//$logo = new EscposImage("images/productos/tostao.jpg");
							$printer = new Escpos();
							/* Print top logo */
                            $printer -> setJustification(Escpos::JUSTIFY_CENTER);
                            //$printer -> graphics($logo);
							$printer -> selectPrintMode(Escpos::MODE_DOUBLE_WIDTH);$printer -> text("RESUMEN PARCIAL\nDE CAJA");$printer -> feed();
							$printer -> selectPrintMode();
							$printer -> setJustification(Escpos::JUSTIFY_LEFT);
							$printer -> feed();
							$printer -> text("Cajero: Javier Jesús Alvarez Montenegro\n");
							$printer -> feed();
							$printer -> text("Caja: Caja Principal  ");
							$printer -> text("# Ref. Caja: 1\n");
							$printer -> feed();
							$printer -> text("Fec.Inic/Fec.Fin: 2015-12-13 02:33:14 - 0000-00-00 00:00:00 \n");
							$printer -> feed();
							$printer -> text("Tick.Inic/Tick.Fin: 1 - 3 \n");
							$printer -> text("# Tickets (Totales): 3");
							$printer -> feed();
							$printer -> text("# Tickets Anul.: 1");
							$printer -> feed();
							$printer -> text("Monto Tickets Anul.: S/.6.00");
							$printer -> feed();
							$printer -> text("# Personas: 1.(No se cont. Paseo bote)\n");
							$printer -> text("------------------------------------------\n");
							$printer -> setEmphasis(true);
							$printer -> text("Cant.     Concepto                 Total\n");
                            $printer -> setEmphasis(false);$printer -> text(" 1   Ingreso General           S/.3.00 \n");$printer -> text(" 6   Paseo en bote             S/.30.00 \n");$printer -> text("------------------------------------------\n");$printer -> setEmphasis(true);$printer -> text("Monto Total Tickets S/. 33.00\n");$printer -> setEmphasis(false);$printer -> feed();$printer -> text("Fecha de Impr.: 13-12-2015 02:37:02\n");$printer -> text("**No válido como documento contable**\n");$printer -> feed();$printer -> cut();$printer -> close();